SHOUT(1)
========
:doctype: manpage

NAME
----
shout - prints large alphanumeric characters to terminal

SYNOPSIS
--------
*shout* [-h | --help] | 'string' ['clear_screen' ['cursor_off']]

DESCRIPTION
-----------
shout takes a *string* argument and prints it to the terminal
using color escape sequences (VT100 compatible).

The following characters can be printed:

*0123456789+-=_.,:;!?/\[](){}abcdefghijklmnopqrstuvwxyz** (and space)

*If 'string' is '-', stdin will be used

Prefixed with the escape character *\* (backslash), the following characters or 'tags' are interpreted for highlighting or inverting:

*\[...\]*: background red

*\\{...\\}*: background green

*\(...\)*: background blue

*\<...\>*: invert the foreground/background color scheme

Any input enclosed with these characters is highlighted.
Highlighting can not be nested.
On closing the hightlight, the color scheme reverts to standard (light gray on black).
Simplified notation is possible by using only the start tag, see examples.
Strings enclosed in \<\> can contain highlighted parts.

If the terminal width is not wide enough for displaying the input on 
one line, the output will look weird.

shout version is 0.4

OPTIONS
-------
*-h, --help*::
	Show help (if given as only argument)
*-v, --version*::
	Show version (if given as only argument)
*-i, --info*::
	Show info (if given as only argument)
*clear_screen*::
	If equal 1, the screen will be cleared and cursor put to top left 
	before output takes place
*cursor_off*::
	If equal 1, the cursor will be hidden (stays hidden after program exits)

EXIT STATUS
-----------
*0*::
	Success

*1*::
	No input string given

EXAMPLES
--------

Simple shout::
	$ shout "123 abc"

Use special symbols::
	$ shout "+-?()[]{}"

Highlight part in string::
	$ shout "1\[2\]3"

Colorful (simplified notation, no closing tags)::
	$ shout "\[ \\{ \( "

Partial color inversion in string::
	$ shout "123\<4567"

Highlighted parts inside inversion::
	$ shout "\[5\(6\) \<\[5\(6\>"

Using options, clear screen before print::
	$ shout "123" 1

Using options, hide cursor::
	$ shout "123" 0 1

Multiline output::
	$ shout 123; shout 456

Read from stdin::
	$ echo "abc" | shout -

BUGS
----
See the BUGS file in the source distribution.

AUTHOR
------
shout was written by Thomas Brand <tom@trellis.ch>

RESOURCES
---------
Github: <https://github.com/7890/shout>

SEE ALSO
--------
*osctermd*(1)

COPYING
-------
Copyright \(C) 2013 Thomas Brand. Free use of this software is
granted under the terms of the GNU General Public License (GPL).

////
example asciidoc manpage
http://www.methods.co.nz/asciidoc/manpage.txt
a2x --doctype manpage --format manpage shout.man.asciidoc
////
